<?php

/**
 * Implementation of hook_boot().
 *
 * Ask for user credentials and try to authenticate.
 */
function httpauth_boot() {
  // Allow cron
  if (basename($_SERVER['PHP_SELF']) == 'cron.php') {
    return;
  }

  // Allow drush
  elseif (isset($_SERVER['argc'])) {
    if (php_sapi_name() == 'cli' || (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)) {
      return;
    }
  }

  if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {
    $query = "SELECT pass FROM {users} WHERE name = '%s'";
    $result = db_result(db_query($query, $_SERVER['PHP_AUTH_USER']));
    if (md5($_SERVER['PHP_AUTH_PW']) == $result) {
      return;
    }
  }

  header('WWW-Authenticate: Basic realm="Non-production Environment"');
  header('HTTP/1.0 401 Unauthorized');
  exit;
}
